export const SERVER_HOST = 'ws://192.168.0.249:9000';
export const BACKGROUND_COLOR = '#040404';
export const PLAYER_COLOR = '#ffffff';
export const BALL_COLOR = '#ffffff';
export const TEXT_COLOR = '#ffffff';
export const MAP_WIDTH = 600;
export const MAP_HEIGHT = 600;
export const INITIAL_SPEED = 5; // ball speed
export const PLAYER_SPEED = 300; // units/s
export const FPS = 60;
export const LOOP_PERIOD = 1 / FPS;
export const CLIENT_SIDE_PREDICTION = true;
export const RECONCILIATION = true;
export const INTERPOLATION = true;
